name: CI

on:
  push:
    branches:
      - release/**
    paths-ignore:
      - "**.md"
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - release/**
env:
  STEP_TIMEOUT_MINUTES: 60
  BUILD_VERSION: '1.0'
  DOTNET_VERSION: 8.0.x
  XCODE_VERSION: 14.3
  DOTNET_VERSION_TARGETS: net8.0
  CSPROJ_TO_BUILD: PATH_TO_PROJECT_FILE
  PROJECT_FOLDER: PROJECT_FOLDER_NAME

jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:      
      buildVersion: ${{ env.BUILD_VERSION }}
      dotnetVersion: ${{ env.DOTNET_VERSION }}
      xcodeVersion: ${{ env.XCODE_VERSION }}
      dotnetVersionTargets: ${{ env.DOTNET_VERSION_TARGETS }}
      csprojToBuild: ${{ env.CSPROJ_TO_BUILD }}
      projectFolder: ${{ env.PROJECT_FOLDER }}
    steps:
      - run: echo "Exposing env vars, because they can't be passed to nested workflows."
      
  build-android:
    needs: vars
    uses: ./.github/workflows/cd-android.yml
    with:
      dotnet-version: ${{ needs.vars.outputs.dotnetVersion }}
      dotnet-version-target: ${{ needs.vars.outputs.dotnetVersionTargets }}
      project-file: ${{ needs.vars.outputs.csprojToBuild }}
      project-folder: ${{ needs.vars.outputs.projectFolder }}
      build-config: 'Release'
      build-version: ${{ needs.vars.outputs.buildVersion }}
    secrets:
      keystore: ${{ secrets.PLAY_KEYSTORE }}
      keystore-alias: ${{ secrets.PLAY_KEYSTORE_ALIAS }}
      keystore-password: ${{ secrets.PLAY_KEYSTORE_PASS }}
      playstore-service-account: ${{ secrets.PLAYSTORE_SERVICE_ACC }}
      
  publish-android:
    runs-on: windows-latest
    name: Android Publish

    steps:
    - name: Setup .NET ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - uses: actions/checkout@v3
      name: Checkout the code

  # This step might be obsolete at some point as .NET MAUI workloads 
  # are starting to come pre-installed on the GH Actions build agents.
    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources

    - name: Restore Dependencies
      run: dotnet restore ${{ inputs.project-file }}
      
    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileDir: '${{ github.workspace }}\${{ inputs.project-folder }}'
        fileName: 'ourkeystore.jks'
        encodedString: ${{ secrets.keystore }}
        
    - name: Version the app
      uses: managedcode/MAUIAppVersion@v1
      with: 
        csproj: ${{ inputs.project-file }}
        version: ${{ github.run_number }} # to keep value unique
        displayVersion: ${{ inputs.build-version }}.${{ github.run_number }}
        printFile: true # optional
        
    - name: Publish MAUI Android AAB
      run: dotnet publish ${{inputs.project-file}} -c ${{ inputs.build-config }} -f ${{ inputs.dotnet-version-target }}-android /p:AndroidPackageFormats=aab /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=ourkeystore.jks /p:AndroidSigningKeyAlias=${{secrets.keystore-alias}} /p:AndroidSigningKeyPass="${{ secrets.keystore-password }}" /p:AndroidSigningStorePass="${{ secrets.keystore-password }}" --no-restore
      